name: seven__columns
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^4.1.2+1
  cloud_firestore: 
  cupertino_icons: ^1.0.0

  flutter_bloc: ^6.1.2
  equatable: ^1.2.6
  dartz: ^0.9.2

  google_fonts: ^1.1.2
  firebase_auth:   
  firebase_core: ^0.7.0
  firebase: ^8.0.0
  provider: ^4.3.2+3
  
  shared_preferences: ^0.5.12+4
  curved_navigation_bar: 
  #connectivity: ^2.0.2
  #http: ^0.12.2
  #get_it: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  mockito: ^4.1.3

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/7Columns.png"

flutter:
  uses-material-design: true

  assets:
   - assets/
  #   - images/a_dot_ham.jpeg
